### ISSUE TITLE
Error for uncertified user trying to submit metadata

### ISSUE THREAD

**Issue by xdoan** [Sage-Bionetworks/data_curator#106]

**Comment by ychae** [comment]
@milen-sage I think there is a way to programmatically check if a user is certified (there's a REST call that looks promising: https://docs.synapse.org/rest/PUT/user/id/certificationStatus.html). I know some user status items are restricted to admins/governance folks only and this might be the case. 

We can follow up with the Synapse team to see if there's a python call for it.

**Comment by ychae** [comment]
From Jordan:

> while there is not a helper method for this the [API](https://rest-docs.synapse.org/rest/GET/user/id/certifiedUserPassingRecord.html) can be invoked e.g.:
```python
response = syn.restGET(f'/user/{user_id}/certifiedUserPassingRecord')
print(response['passed'])
```
>Provided that you have the user's profile id

**Comment by milen-sage** [comment]
oh nice! @sujaypatil96 and @xdoan where do you see this functionality live?

My first instinct is to
1. incorporate it as a check on schematic's side when calling the store.py associateMetadata... method
2. have the method return an error that can be displayed in a user friendly way on the front-end data curator app side

@BrunoGrandePhD this might be relevant when thinking about imCORE SOPs as well (i.e. ensuring users are certified when trying to submit metadata). @ychae had already added language around that in the data ingress docs.

**Comment by ychae** [comment]
Function from @jaeddy :

```R
synGetCertificationStatus <- function(owner_ids) {
  get_certification_status <- function(owner_id) {
    request <- str_glue("/user/{id}/certifiedUserPassingRecord", id = owner_id)
    res <- list(passed = FALSE)
    try(res <- synRestGET(request), silent=TRUE)
    res$passed
  }
  if (is_vector(owner_ids)) {
    map_lgl(owner_ids, get_certification_status)
  } else {
    get_certification_status(owner_id)
  }
}
```

**Comment by ychae** [comment]
And a python version from @thomasyu888 located here: https://github.com/Sage-Bionetworks/challengeutils/pull/204/files

**Comment by sujaypatil96** [comment]
Thanks for sending the snippets above @ychae.

> My first instinct is to
> 
> incorporate it as a check on schematic's side when calling the store.py associateMetadata... method
> have the method return an error that can be displayed in a user friendly way on the front-end data curator app side

Yup, that makes sense @milen-sage. We should incorporate the check on `schematic` side, but instead of `associateMetadataWithFiles()` we should probably do it in the constructor itself? It's important that all users by Synapse-certified.

**Comment by xdoan** [comment]
Yeah we might even be able to show it at the beginning landing page? like "! you are not certified"

**Comment by xdoan** [comment]
Tom just submitted code for this feature in the Python client: https://github.com/Sage-Bionetworks/synapsePythonClient/pull/801/files
