### ISSUE TITLE
Improve error handling on manifest missing required columns/wrong schema errors

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/data_curator#133]
Open a new issue to improve error message when uploaded manifest does not have all required columns and 'wrong schema' errors are given from backend.

> When we try validating manifests that were submitted using a previous version of a schema we get the "wrong schema" error in addition to a message saying "An error has occurred. Check your logs or contact the app author for clarification." This isn't a situation that most people would encounter once the schemas are finalized (we mostly encounter it since we and others have been testing with schemas that were still in flux), but I agree we should have better error handling.<br><br>It's fine to indicate that the schema used by a manifest is not the right one (i.e. it's wrong) given the selected schema in step 1. But we probably shouldn't be getting "Check your logs..." error. <br><br>The message "At row 2 value Wrong schema in Wrong schema <<column name>> is a required property", can be changed (which is probably the intent of this issue :). If the backend returns "wrong schema", we shouldn't try to interpret at which row and which value the error occurred. Perhaps an informative message would be "The submitted manifest doesn't contain required columns: <<column1, column2, column2>>. Please check that you have selected the correct template type and  ensure your template contains the required columns"; the header row in the preview table can be highlighted with the bright yellow we already use for validation errors.<br><br>Once we start versioning schemas and including the version information with the metadata we can have more informative messages, but for now this could be ok? <br><br>_Originally posted by @milen-sage in https://github.com/Sage-Bionetworks/data_curator/issues/61#issuecomment-656207143_

**Comment by milen-sage** [comment]
Thanks for re-opening @rrchai !

**Comment by rrchai** [comment]
Now, the error indicates it is wrong schema relevant errors because of missing required columns.

Create a new ticket if we consider to be more specific/descriptive on wrong schema errors, e.g. outdated schema vs wrong column names vs miss required columns.
