### ISSUE TITLE
Abstract redundant code in reusable global functions and variables

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/data_curator#138]
Some redundant codes can be called once as global variable and change the global variable in the server, which make codes cleaner, e.g selected template.

**Comment by sujaypatil96** [comment]
This is linked to issue #145. I would recommend tackling this after we have reviewed and merged that issue in order to avoid duplicating effort.

**Comment by rrchai** [comment]
see issues #145 #146
