### ISSUE TITLE
Data Curator App documentation improvement

### ISSUE THREAD

**Issue by sujaypatil96** [Sage-Bionetworks/data_curator#147]
1. Update documentation theme to match theme as [here](https://nf-data-portal-docs.scrollhelp.site/NFdocs/). A site powered by Scroll Viewport and Atlassian Confluence.
2. Decide on branch naming convention. Recommended convention is specified in [gitflow](https://nvie.com/posts/a-successful-git-branching-model/) docs.
3. Remove all references to HTAN (de-HTAN-ify) the codebase including the docs.

**Comment by milen-sage** [comment]
Closing this issue since we've established branch naming conventions; have generic de-HTAN-ified documentation; and have templates for docs.
