### ISSUE TITLE
error handling improvement for user without access to projects to annotate

### ISSUE THREAD

**Issue by kthrog** [Sage-Bionetworks/data_curator#148]
If you access the data curator app while logged into Synapse, but do not actually have access to any projects connected to that app, it just 'generates' forever. Seeing a descriptive error might be nice -- something like, 'you may need access to a Synapse project to use this app.' I think this might be the same as / connected to issue #94 but I'm not 100% sure on that.

![image](https://user-images.githubusercontent.com/43977698/114102471-3bb4bf80-987c-11eb-8982-0ec20ad47b77.png)

**Comment by rrchai** [comment]
replaced by #338
