### ISSUE TITLE
metadataModelFuns.py config bug

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/data_curator#156]
Maybe I have done something wrong, but i had to change L11 to a more explicit path, rather than referring to the schematic config:

`inputMModelLocation = "./schematic/data/schema_org_schemas/...schema name....jsonld"`

in order to get the front end app to work with the newer-style schematic config file. Prior to that, I would get this error: 

```
Error in py_run_file_impl(file, local, convert) :
  FileNotFoundError: [Errno 2] No such file or directory: 'data/schema_org_schemas/NF.jsonld'
```

**Comment by milen-sage** [comment]
@allaway I think this should be resolved with newer versions of schematic and DCA. I'll close for now, but if you bump into anything similar in your testing of newer versions, we can reopen or open a new issue.
