### ISSUE TITLE
large manifest files crash app @ validation stage

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/data_curator#160]
I tried to validate this manifest: https://docs.google.com/spreadsheets/d/1UtYc889bzhUms67bBbHYvyx46eUncztDOSo5KH2xPHM/edit#gid=136843556

If I make a 'mini-manifest' of only the first 70 rows (e.g. one of the subfolders), validation works fine. 

However, if I try the full manifest (561 rows), after clicking "validate" the app crashed. This log shows both the successful validation (eg mini-manifest), and the failure (the full manifest). Unfortunately, the only error is `execution halted`...which is not super helpful. :( 

Any ideas?

**Comment by allaway** [comment]
Oops, here is the log: 

```
Listening on http://127.0.0.1:45177
INFO: [2021-04-27 16:56:22] synapseclient_default - Welcome, Robert Allaway!

[WARNING] sys:1: DtypeWarning: Columns (7,27,34,36,37,38,40,42,44,45,49,50,52) have mixed types.Specify dtype option on import or set low_memory=False.

WARNING: [2021-04-27 16:56:25] py.warnings - sys:1: DtypeWarning: Columns (7,27,34,36,37,38,40,42,44,45,49,50,52) have mixed types.Specify dtype option on import or set low_memory=False.

Warning: Error in [[: subscript out of bounds
  96: renderUI [/home/rallaway/ShinyApps/NF_data_curator_staging/app.R#373]
  95: func
  82: origRenderFunc
  81: output$folders
   1: runApp
Parsed with column specification:
cols(
  .default = col_character(),
  reportMilestone = col_logical(),
  modelSystemName = col_logical(),
  modelSystemStrainNomenclature = col_logical(),
  genePerturbationType = col_logical(),
  genePerturbationTechnology = col_logical(),
  genePerturbed = col_logical(),
  isCellLine = col_logical(),
  isPrimaryCell = col_logical(),
  experimentalCondition = col_logical(),
  experimentalTimepoint = col_logical(),
  timePointUnit = col_logical(),
  readPair = col_logical(),
  isStranded = col_logical(),
  readStrandOrigin = col_logical(),
  dissociationMethod = col_logical()
)
See spec(...) for full column specifications.
Parsed with column specification:
cols(
  .default = col_character(),
  reportMilestone = col_logical(),
  modelSystemName = col_logical(),
  modelSystemStrainNomenclature = col_logical(),
  genePerturbationType = col_logical(),
  genePerturbationTechnology = col_logical(),
  genePerturbed = col_logical(),
  isCellLine = col_logical(),
  isPrimaryCell = col_logical(),
  experimentalCondition = col_logical(),
  experimentalTimepoint = col_logical(),
  timePointUnit = col_logical(),
  readPair = col_double(),
  isStranded = col_logical(),
  readStrandOrigin = col_logical(),
  dissociationMethod = col_logical(),
  accessTeam = col_double(),
  age = col_double(),
  isMultiIndividual = col_logical(),
  isMultiSpecimen = col_logical()
)
See spec(...) for full column specifications.


Execution halted

```

**Comment by rrchai** [comment]
Hi Robert,

I am trying to reproduce the errors and dig into the reason. Could you tell me which template type you chose to validate?

Thanks

**Comment by allaway** [comment]
Hi Rong, 

I'm using the nf GenomicsAssay template, here's where it is defined: https://github.com/nf-osi/schematic/blob/93afd59f44d3329303075733adf48a0ee769518a/data/schema_org_schemas/NF.jsonld#L8534

**Comment by rrchai** [comment]
Hi Robert,

I am not able to reproduce the errors on my side. All errors(1k+) from "full-manifest" can be printed during validation process, but it did take much longer than "mini-manifest" (100+ errors). I am not sure if large amounts of errors is the reason to cause the app crash. If it is the case, we are working on to compress the duplicated errors #144 and hope it will solve the issue.

I wonder what is code in the Line #373 of your app.R since log mentioned:
```
Warning: Error in [[: subscript out of bounds
  96: renderUI [/home/rallaway/ShinyApps/NF_data_curator_staging/app.R#373]
```

**Comment by allaway** [comment]
Hi Rong,

Interesting. Glad it works on your side...it must be something funky with my fork, perhaps. 

I think the error you linked is caused by typing in the project name in the selectizeInput and is unrelated to this issue. Here's a gif: 

![Screen Recording 2021-04-28 at 2 38 38 PM](https://user-images.githubusercontent.com/20408008/116476303-e3942c00-a82f-11eb-9ab6-35355c6216d1.gif)

**Comment by allaway** [comment]
Wow, not sure what happened there but i think the gif conversion slowed that down by 2x or something...sorry

**Comment by allaway** [comment]
I've assigned this to myself b/c it sounds like it might be an issue on my end.

**Comment by allaway** [comment]
Good news! I updated to `shiny-server-develop` and made the necessary changes for NF and it seems to be working fine now! 

One question: when I click validate, the `waiter` doesn't seem last long enough, it should probably disappear after the error table is rendered but it actually disappears sooner and then it seems like the app has frozen for several seconds. Do you see this on your end too?

**Comment by rrchai** [comment]
@allaway sorry about the late reply. It seems like the issue of app crash due to large manifest is solved on your end?

> @rrchai : One question: when I click validate, the waiter doesn't seem last long enough, it should probably disappear after the invalid metadata reporting table is rendered but it actually disappears sooner and then it seems like the app has frozen for several seconds. Do you see this on your end too?

The container displaying the errors are shown after the waiter screen is hidden, but the process to generate the error is completed before the water screen hidden. On my end, I did not see the app frozen for several seconds. If you still have the same issue, please let me know and I can dig into the reason.

**Comment by allaway** [comment]
@rrchai Tahnks for the info! I don't think that bug happens anymore in the latest version of the app. I will reopen if needed!
