### ISSUE TITLE
App crashes if uploading manifest without any existing file/data in the folder

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/data_curator#172]
If the dataset has no files existed, uploading validated manifest will crash because `stack` doesn't like `NULL`.

https://github.com/Sage-Bionetworks/data_curator/blob/dbd19831302e3e4cd37df5b550e8c22dc8abb738/server.R#L306-L313

Since some folders could be empty before uploading manifest, such as clinical and biospecimen data, and I feel it is better to have errors before submitting the manifest. Let's cycle back to this issue when we work on better filenames checking, related to the issues #142 and #30.

**Comment by milen-sage** [comment]
Acceptance criteria - the app no longer crashes.

**Comment by lakikowolfe** [comment]
Code in pull req 270 solves the issue of the app crashing when no manifest is present in the selected fileview.

Screenshots of what dashboard looks like when it renders with no manifest present:

![Screen Shot 2022-02-18 at 11 37 56 AM](https://user-images.githubusercontent.com/30699094/154750854-51338148-0b9d-4475-9451-c71d6408e78e.png)

![Screen Shot 2022-02-18 at 11 38 06 AM](https://user-images.githubusercontent.com/30699094/154750886-7301d23c-7181-43f2-bbbb-6a474bf3fe35.png)

![Screen Shot 2022-02-18 at 11 38 18 AM](https://user-images.githubusercontent.com/30699094/154750907-1fdac904-cde2-49c2-91e9-b22de251a8cd.png)

**Comment by milen-sage** [comment]
0% is indeed something deserving a crown! :) 

I think this looks good for the purposes of this issue. 

We will start a separate issue on dashboard "gamification" and the respective iconography and status messages - we can align on user messages across the three tabs as part of that work.

@rrchai what do you think?
