### ISSUE TITLE
Disconnection when there is no existing manifest

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/data_curator#206]
All tests were done on the test folder located here: [syn26004567](https://www.synapse.org/#!Synapse:syn26004567). 

### Tests 
Several templates disconnected when generating the metadata template (these also disconnected on the production app) :
- [x] Bulk RNAseq level 1
- [x] scRNAseq level 1
- [x] Imaging level 2

_Originally posted by @ychae in https://github.com/Sage-Bionetworks/data_curator/issues/205#issuecomment-937340213_

**Comment by milen-sage** [comment]
@rrchai yes, I am testing today, meanwhile if you could just confirm you are on the latest version of the  schematic`develop` branch (that has the syn_store error fixed) in the developer version of the app?

**Comment by milen-sage** [comment]
@rrchai this is a good point! I'll issue a PR to fix this. This is critical and once the fix is in we'd have to update the DC app to the latest version of schematic's `develop` branch.

**Comment by milen-sage** [comment]
@rrchai, when you have a moment could you update a develop version of the DC app to latest schematic `develop`? This has [PR#532](https://github.com/Sage-Bionetworks/schematic/pull/532) merged. @ychae and I can test it.

**Comment by milen-sage** [comment]
@rrchai ok, if you are satisfied with testing behavior, feel free to update production instances. 

Do you see an easy-ish, good way to address 

> if a user tries to generate a manifest for a **file-based data type** (e.g. scRNA-seq) ... the DC app can alert the user that they should first upload data files for the selected data type, before they can actually generate a manifest

With the current behavior, in the above scenario^ w/o alert, the downside is that users may download the generated empty manifest and populate filenames manually (i.e. no entityIds will be fetched from Synapse). If they submit their manifest, it may get validated, but its contents will not be associated with entityIds on Synapse. The latter would cause problems downstream.

I guess that boils down to the DC app knowing 

a. the selected data type requires files to be uploaded first
b. know that files have not been uploaded yet

b. is easy, and I think the DC app already get's a list of files. Do you know if any place in the DC app config, we indicate which data types/schema components are "file-based" vs "record-based" (e.g. Clinical data)?

**Comment by rrchai** [comment]
Thanks for quick fix @milen. I have updated the prod site as well.

I can start to improve on error handling based on your suggestions tomorrow.
