### ISSUE TITLE
504 Gateway Time-Out when generating template

### ISSUE THREAD

**Issue by brynnz22** [Sage-Bionetworks/data_curator#223]
**Describe the bug**
- [ X] Server disconnect
- [ ] Wrong manifest
- [ ] Wrong values in manifest columns
- [ ] Other (please describe)

**To Reproduce**
Center: Vanderbuilt
Template: Exposure

**Screenshots (optional)**

**Additional context (optional)**
Could not generate template. Tried to reload the app - got "504 Gateway Time-out"

**Comment by rrchai** [comment]
followed up [jira ticket](https://sagebionetworks.jira.com/browse/IT-1520) and ticket #241

**Comment by milen-sage** [comment]
With the switch to shinyapps.io this has been resolved. We are also moving towards a more scalable app deployment w/in Sage IT's Fargate AWS architecture where this won't be an issue.
