### ISSUE TITLE
Mismatched field name and drop down options

### ISSUE THREAD

**Issue by clarisse-lau** [Sage-Bionetworks/data_curator#226]
**Describe the bug**
- [ ] Server disconnect
- [ ] Wrong manifest
- [ ] Wrong values in manifest columns
- [X] Other (please describe)

**To Reproduce**
Center: OHSU
Template: Demographics

**Screenshots (optional)**
![Screen Shot 2021-11-15 at 10 18 07 AM](https://user-images.githubusercontent.com/63608514/141834179-a1163fbf-e699-405c-8994-370633f6a71d.png)
![Screen Shot 2021-11-15 at 10 20 54 AM](https://user-images.githubusercontent.com/63608514/141834189-82b4e734-5cf3-4131-b58f-065f673802ba.png)

**Additional context (optional)**
Drop down options and field description don't align with column name in Google sheets template

**Comment by milen-sage** [comment]
This would have been an error in schematic working with the schema, but it should have been resolved in newer versions. Closing this issue until we see the bug resurfaces, if it does, in the future.
