### ISSUE TITLE
Invalid conda env key name in global.R

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/data_curator#235]
**Describe the bug**
key name in `example_config.yaml` does not match the key used in `global.R`. It will cause invalid conda environment used. 
https://github.com/Sage-Bionetworks/data_curator/blob/106e701b686e29653a4d42c031e43792ec5f95d2/example_config.yaml#L11

 https://github.com/Sage-Bionetworks/data_curator/blob/106e701b686e29653a4d42c031e43792ec5f95d2/global.R#L46

**Expected behavior**
The key name for conda env name value should be changed from `CONDA_ENV_NAME` to `CONDA_ENV`.

**Comment by afwillia** [comment]
Note: toString(NULL) returns "" which is why this slipped past the error handling `if(is.null(conda_name)) ...`
