### ISSUE TITLE
Profile app with shinyloadtest to test latency issues with concurrent users

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/data_curator#241]
There are reports of the app sending a 504 disconnect error when multiple users are accessing it simultaneously. Look into shinyloadtest to document potential bottlenecks.

**Comment by afwillia** [comment]
Profiling the app with <5 users yields consistently good results. However, with >5 latency issues pop up and shinycannon cannot complete the tests, returning messages like `WS_RECV line 82: Haven't received message after 30 seconds`. High latency apps are a [known issue](https://rstudio.github.io/shinyloadtest/articles/limitations-of-shinyloadtest.html) for shinyloadtest.

Notably, running shinycannon in the office yields much better results than my home connection. Not only do fewer sessions hang indefinitely with the above message, but the app executes much faster.

**Comment by ychae** [comment]
- [ ] what points are hanging up?
Acceptance Criteria:
1. Document fx or calls to synapse that are stalling

**Comment by afwillia** [comment]
@ychae @milen-sage Swapping `metadata_model$getModelManifest` with [the schematic REST API](https://github.com/Sage-Bionetworks/schematic/blob/183e5aad1c6ebe187563431fdb916453809fcb23/api/routes.py#L47), using very limited, hard-coded functionality did not result in much of a difference in execution time or latency issues with multiple users.

The same Synapse query is getting downloaded by DCA and the manifest API call. It's a 14.2kB dataset, but its worth exploring it's contribution to latency issues. I think it's coming from this part of [synapse store ](https://github.com/Sage-Bionetworks/schematic/blob/183e5aad1c6ebe187563431fdb916453809fcb23/schematic/store/synapse.py#L73). Maybe we can cache this dataset somewhere.

**Comment by afwillia** [comment]
@rrchai found similar issues in April https://github.com/Sage-Bionetworks/data_curator/issues/139
