### ISSUE TITLE
Add error handling for expired oauth token

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/data_curator#246]
**Describe the bug**
If you load a url with an expired oauth token, for example, if you refresh the app the app will disconnect without warning.

**To Reproduce**
1. Load the app, login. 
2. Refresh the app.
3. Or just navigate here https://shiny.synapse.org/users/rallaway/NF_data_curator/?state=qxJOqdKlio&code=557bfa04-eea6-4df5-8d77-5d1745667eda

**Expected behavior**
 It would be great if this was handled more gracefully (e.g. detect invalid token, punt users to login page).

**Additional context**

I'm posting this over in the projectlive.modules repo as well, so perhaps the solution could be the same as that one (https://github.com/Sage-Bionetworks/projectlive.modules/issues/36).

**Comment by ychae** [comment]
@allaway Could you give us the level of priority for this request?

**Comment by allaway** [comment]
I'd call it low-medium, quality of life type improvement. :)

**Comment by allaway** [comment]
Hi @ychae , I just discovered that the stale oauth state/code in the URL also breaks the "Reload app" link when the app disconnects (e.g. this link refreshes the page, keeping the same code in the URL). Ideally, the app should detect that it's being handed a stale token, and try to get a new one/re-prompt for login. 

With that in mind, I'd probably upgrade this to high priority. 

Cheers,
Robert

**Comment by ychae** [comment]
@allaway Thanks for catching that! I'll bump it up and see when we can get a fix deployed.

**Comment by ychae** [comment]
@rrchai and @milen-sage I know we've got a few things actively being worked on right now (and Home Week fast approaching around the corner!) so we won't have time for it in this cycle. But would either of you be able take a look at this in the next couple of work days and provide an estimate on the amount of work it would take to fix it? I'd like to see if it's a fix we can get in for the next cycle.

**Comment by rrchai** [comment]
@ychae I should’ve linked PR #204 here, but that PR has addressed this issue

@allaway Adding below snippet into the `dashboardBody` will clear the url after 2s app initiates:

https://github.com/Sage-Bionetworks/data_curator/blob/106e701b686e29653a4d42c031e43792ec5f95d2/ui.R#L92

Let me know if that works :)

**Comment by allaway** [comment]
🙌 nice work @rrchai ! I'll update to the latest version of the develop app and close this issue if it works!!

**Comment by ychae** [comment]
Wow that's great! Thanks @rrchai!
