### ISSUE TITLE
Interface app with schematic's REST API

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/data_curator#249]
The app currently interfaces with schematic through reticulate and as a result requires the host to install schematic and its dependencies. This is problematic if the host cannot install system libraries, for example on shinyapps.io. Using schematic's REST API with, for example, `httr`, would drastically simplify installation of the app by removing all python dependencies. First we need to determine which schematic endpoints Data Curator App requires and which are exposed through the REST API.

**Comment by milen-sage** [comment]
@afwillia closing this issue since we have others opened for that.
