### ISSUE TITLE
Default config.json does not match  example.model.jsonld

### ISSUE THREAD

**Issue by lakikowolfe** [Sage-Bionetworks/data_curator#255]
**Describe the bug**
When installing DCA locally the default example files do not align.

For example: `config.json` contains the schema name `BulkWESLevel1`. This isn't present in the example.model.jsonLd and selecting it breaks DCA.

**To Reproduce**
1. Install DCA
2. Launch DCA
3. Go to `Select Dataset`
4. Under `Choose Metadata Template` you will see options that are not in the `example.model.jsonld` and will kill the app.

**Expected behavior**
I would expect that these two files would be populated with example data that works together upon initial installation.

**Screenshots**
NA

**Desktop (if applicable, please complete the following information):**
 - iOS
 - Chrome
 - Not totally sure which version, where can I find this info? This was recently pulled from `shiny-server-main`.

**Comment by milen-sage** [comment]
Config file has been updated to match example data model. We can open a new issue to automatically generate the content of the config file based on the data model.
