### ISSUE TITLE
Requirements Gathering on Data Release Dashboard Prototype

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/data_curator#257]
A ticket to track the requirements output from meeting with @adamjtaylor on HTAN. 

**Current prototype**
[Issues](https://github.com/ncihtan/data-release-tracker/issues)
[Project board](https://github.com/ncihtan/data-release-tracker/projects/1)
[Milestones (by center)](https://github.com/ncihtan/data-release-tracker/milestones)

**Comment by ychae** [comment]
Acceptance criteria:
Outline/Enumerate the use cases that come out of these conversations

**Comment by lakikowolfe** [comment]
## Notes from meeting with Adam

*Overarching goal is to provide a quick view of which datasets are ready to release vs those that need more work and what work is left to do*

Adam set up the GH based tracking system:
- queried master HTAN file view to obtain synapse storage manifests
- pulled from HTAN portal list of every synapse id of every released file
- read every manifest and counted how many files were released or not released, saved results as a table
- using the github CLI generate an issue for each manifest including standardized title and body w table created in previous step and assigned to milestone/center
- manually added labels to issues

"mixed manifest": A manifest that already existed and now has newly added files. This is the most difficult for the current system to asses. Adam manually reviews these.

Need to close the loop between HTAN center and Sage. How are we alerting HTAN centers that their data is ready for release? How are the HTAN centers alerting us which data they want released?

### Use cases

-
