### ISSUE TITLE
installation notes: feat-UI-dashboard

### ISSUE THREAD

**Issue by lakikowolfe** [Sage-Bionetworks/data_curator#258]
Notes from installing `feat-UI-dashboard` branch of DCA

**Comment by ychae** [comment]
Acceptance criteria:
DCA launches and dashboard renders
Add in additional documentation

**Comment by lakikowolfe** [comment]
## initial installation 

did no know what exactly needed to be repeated if you're installing a second data curator on your machine.
* can I use the same client Id/secret (You can)
* do I need to recreate the conda environment (I don't)

## Running the app in RStudio

* required to update shiny
* On click of `run app`, application begins to load and then errors out with this error: 

```
This Font Awesome icon ('gears') does not exist:
* if providing a custom `html_dependency` these `name` checks can 
  be deactivated with `verify_fa = FALSE`
```
[Problem seems to be related to `shinydashboardPlus`](https://stackoverflow.com/questions/69430064/this-font-awesome-icon-gears-does-not-exist-in-r-shiny). Get around it by downgrading to version 0.7.5.

*
