### ISSUE TITLE
shinyload profile compute footprint of DCA

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#267]
@afwillia has identified the latency bottleneck in #241 !

We can now proceed with profiling 

- [x] RAM
- [ ] CPU
- [x] hard disk 

footprint of the app.

For hard disk, it'd be really good to know how fast would we get to 10GB of hard disc usage given our current fileview query and download practices. This can be best profiled realistically with a large project like HTAN. 

E.g. how fast users that have access to the entire HTAN fileview get to 10GB hard disk space. Suppose we have 10 users that concurrently access the app 5-10 times a day.

**Comment by afwillia** [comment]
Get an `Out of memory!` message on https://sagebio.shinyapps.io/data_curator-staging/ with 2+ users. The memory usage on shinyapps.io dashboard shows ~500MB max.

**Comment by afwillia** [comment]
The app disconnects when 2+ users try to generate the google sheet at the same time (at least for two sessions in my browser).

**Comment by afwillia** [comment]
Profiling one local run with `top` shows that the R session uses 500MB and the python session 427MB. So converting the reticulate calls to use schematic's REST API would make a nice dent in that.

**Comment by afwillia** [comment]
@milen-sage 10 users, 5X/day = 50 accessions per day. I cleared my .synapseCache and then ran DCA for 10 different projects. After 1 round of template generation, the cache is 1.3GB. Running the same steps again to simulate the same users, the cache grew to 2.7GB.

1.35 * 10 * 5 = 67.5 GB per day * 30 = 2TB/month.... So under 2 days to get to 10GB.

Granted, this is an upper bound because I have access to the entire fileview, while most users can only access their projects.

**Comment by afwillia** [comment]
> Get an `Out of memory!` line in the log on https://sagebio.shinyapps.io/data_curator-staging/ with 2+ users. The memory usage on shinyapps.io dashboard shows ~800MB max. We definitely exceed the 1GB limit with concurrent users. 

Good news, we have a paid version now and the max memory is now 8GB. After setting our instance to 8GB, I'm able to run the app with 6 instances in my browser.

**Comment by milen-sage** [comment]
@afwillia this is really good to know - this is all in terms of RAM right? 

What are they using in their free tier?! My high-school pentium IV machine?

**Comment by afwillia** [comment]
@ychae This is done. We now know the app maxes at ~800MB memory per session and writes at most ~1.3GB to the disk.
