### ISSUE TITLE
Consolidate steps and documentation on shinyapps.io deployment

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#268]
@rrchai and @afwillia have tested the DCA w/in shinyappps.io and have reported deployment issues (e.g. issues related to PR #250). 

Before moving apps in production to shinyapps.io these issues need to be resolved (or confirmed as resolved) and the deployment process documented.

**Comment by milen-sage** [comment]
Acceptance criteria - finding out what it takes to deploy a shiny app to shinyapps.io; consult with Bruce on the process. Having a README with a checklist for deployment steps.

**Comment by afwillia** [comment]
@ychae This is done and addressed in the file data_curator/shinyapps_deploy.txt

**Comment by afwillia** [comment]
@ychae done and addressed in this branch https://github.com/Sage-Bionetworks/dccvalidator/tree/read_schema_file_url
