### ISSUE TITLE
Validation error despite matching template name and manifest component

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/data_curator#272]
**Describe the bug**
Validating a manifest for template "Clinical Tier 1: Demographics" fails despite the Component column of the manifest matching the name of the template. It appears that if a manifest is already present in a folder, the app silently uses that file, ignoring the template chosen in the dropdown menu.

**To Reproduce**
1. Data curator app -> Project: HTAN Center A, Folder: test-awilliams, template: Clinical Tier 1: Demographics
2. Generate the google sheet (Note that the Component is "Biospecimen" - this appears to be a biospecimen manifest.)
3. Change component to Clinical Tier 1: Demographics and reupload to the data curator validation tab.

**Expected behavior**
I expect the application to match the name of the template to the component in the manifest. Since this folder already contains a biospecimen manifest, an error stating that only one type of manifest is allowed per folder would be helpful. 

**Priority** (select one)
- [ ] Major 📢

**Screenshots**
![Screen Shot 2022-02-16 at 1 44 09 PM](https://user-images.githubusercontent.com/8195343/154364136-aea26d8f-1eac-4cd2-a053-3b37cb1a233c.png)

**Comment by rrchai** [comment]
Copy the conversation from slack to this ticket:

@milen-sage 
> I wonder if it has to do with how names are set in the config file? @rrchai  would that be a possible reason?

yeah, right. In `config.json`, its schema name is “Demographics”. we use schema name to validate the filled metadata, but use display name in the error.

Assuming the correct name of data type is “Demographics” in the component column in the manifest:
If users accidentally fill in with the display name (Clinical Tier 1: Demographics in this case), the error message might be confused.

Purposed solutions:
Replace “Clinical Tier 1: Demographics” with schema name, “Demographics” in the error message; Possibly need to rephrase the error message a bit, and identify they should put schema name in Component.
Ignore this error, it requires some work in the app to filter out the error from schematic; but it will allow users to have inconsistent Component names (personally not recommend)

**Comment by milen-sage** [comment]
Sounds like this has been resolved.
