### ISSUE TITLE
Place manifest into a submission queue if the app is busy, rather than crashing

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/data_curator#281]
**Is your feature request related to a problem? Please describe.**
Users are always frustrated when they attempt to submit their manifest and the server crashes because too many people are trying to submit at once. 

**Describe the solution you'd like**
As a data contributor, I would like to submit my manifest and have it go into a queue if there are lots of people submitting at once, rather than it crashing the server so that I can submit my metadata and not have to schedule my work around less busy app times. 

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Comment by milen-sage** [comment]
With moving to shinyapps.io and increased memory we no longer have an urgent need here. With the subsequent multi-tenant deployment in Sage IT's Fargate-based architecture we no longer need to do that. The app will autoscale. Closing for now and can reopen anew if needed.
