### ISSUE TITLE
Implement Release Administrator UI - alpha

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#286]
**Is your feature request related to a problem? Please describe.**
We'd like to create a new shiny app module: Release Administrator. (@lakikowolfe it turns out release coordinator is already taken by a different service in our INCLUDE project that does very different tasks).

This module addresses the [user scenario here](https://docs.google.com/document/d/1q4IyIIbyH1miL2kXbaBt1yHUhA_8J9Vzfa8q1SnKdUk/edit?disco=AAAAUrhwgv0).

@lakikowolfe has completed requirements and stack research, and has developed initial design mockups #263.  

**Describe the solution you'd like**
The alpha version of the Release Administrator UI should implement the design mock ups [here](https://docs.google.com/presentation/d/1C62QkpKD-65GCtsfyXn_Pb049JF4WKWKIIiosliDPLs/edit?usp=sharing).

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Comment by ychae** [comment]
Link the related tickets here

**Comment by lakikowolfe** [comment]
Related Issues:
#275 
#276
#277
