### ISSUE TITLE
Auto generate config.json 

### ISSUE THREAD

**Issue by lakikowolfe** [Sage-Bionetworks/data_curator#295]

**Comment by rrchai** [comment]
To achieve this issue:
- [ ] I think we only need to figure out how to get all schema names and types
- [ ] if we would like to continue using display names

@milen-sage  what do you think the best way to get all schema names, from data models?

**Comment by milen-sage** [comment]
@milen-sage point @rrchai to the schematic function that returns all data types defined within a given json-ld schema.

**Comment by rrchai** [comment]
The PR is created and can auto generate config.json - @rrchai will need further improved codes based on @milen-sage's suggestions.
