### ISSUE TITLE
In DCA use synapse/schematic REST API instead of python client

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/data_curator#298]
The app uses several functions from the synapseclient module via reticulate. In an effort to eliminate the python/reticulate dependency, we're refactoring the app to use schematic's REST API instead of reticulate calls. The same will need to be done with synapseclient. 

**How important is this feature?** Select from the options below:
• 🌗 Medium - it goes along with using the schematic REST API

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

The functions we'll need to replace are [here](https://github.com/Sage-Bionetworks/data_curator/blob/main/functions/synapse_func_alias.py)

- [x] syn.getUserProfile
- [x] ~[syn.tableQuery](https://github.com/Sage-Bionetworks/synapsePythonClient/blob/3da21b9e2542c7da8cdab9925926737fe2162a54/synapseclient/client.py#L3299)~
- [x] [syn.get](https://github.com/Sage-Bionetworks/synapsePythonClient/blob/d9341683ec3c2c20e92678bc31733741c501e777/synapseclient/client.py#L665)
- [x] syn.is_certified

**Comment by afwillia** [comment]
I don't see any references to `tableQuery` or `get` in [server.R](https://github.com/Sage-Bionetworks/data_curator/blob/main/server.R) or sourced files. Maybe we don't need those.

`getUserProfile` and `is_certified` are only used during the loading screen. The user must be certified and then the welcome screen shows their name.

**Comment by afwillia** [comment]
Addressed in #296 along with the schematic REST API wrappers.

**Comment by milen-sage** [comment]
Acceptance criteria: calls to the Synapse client have been mapped to Synapse REST API calls.

**Comment by rrchai** [comment]
@afwillia Thank you for making it work! I just have two things to add:
- `syn.get` is using in the dashboard. It is good to have this function work as well :)
- Does `syn.login` also have an endpoint already?

I am not familiar with API and I have another question regarding this issue:
Since the synapse already has the restAPI calls, [here](https://docs.synapse.org/rest/), I wonder if it can be used directly for `httr`? Or the endpoints for synapse will be required and used for schematic functions?

**Comment by rrchai** [comment]
> I am not familiar with API and I have another question regarding this issue:
Since the synapse already has the restAPI calls, [here](https://docs.synapse.org/rest/), I wonder if it can be used directly for httr?
ah, nevermind. I think it is what @afwillia has been implementing for the synapse functions.

**Comment by afwillia** [comment]
@rrchai right, `syn.login` isn't necessary with the REST API calls because the authentication is passed with each request. I'll work on `syn.get` though!

**Comment by rrchai** [comment]
@afwillia right, I see!  Thanks for clarification.

**Comment by afwillia** [comment]
I still don't see any references to `tableQuery` in the DCA code beyond defining it in [synapse_func_alias.py](https://github.com/Sage-Bionetworks/data_curator/blob/main/functions/synapse_func_alias.py) However, I think this is the synapse endpoint it will use https://rest-docs.synapse.org/rest/POST/entity/id/table/query/async/start.html

**Comment by milen-sage** [comment]
@afwillia 

> For GET, I used this endpoint https://rest-docs.synapse.org/rest/GET/entity/id.html

This^ works for now, but when @linglp implements schematic's endpoint for getting dataset manifest let's switch to it. That way we can keep DCA a bit more Synapse agnostic and can do some manifest preprocessing, if needed, in schematic.

**Comment by afwillia** [comment]
https://github.com/Sage-Bionetworks/data_curator/blob/c5ba8e72e7934033a03a6b56aff474908932777b/functions/dashboardFuns.R#L7 synStoreObj$storageFileviewTable

**Comment by ychae** [comment]
@afwillia can we confirm that all the REST API endpoints are available? And if they are, are all the necessary endpoints for the dashboard in place?

**Comment by afwillia** [comment]
@ychae Yes, all the endpoints in schematic's develop branch are available. But they haven't been added to the dashboard branch of DCA, yet.

**Comment by ychae** [comment]
@afwillia I see that this is marked as done on the Project Board, would it be okay to close this ticket? (I wish the project board would be bi-directional about this so that marking it done on the board translates to closing a ticket but that's an "upcoming feature" of project board beta...)

**Comment by afwillia** [comment]
I think I prematurely marked this as complete. It's like 95% there but I still need to check if the dashboard functions.

**Comment by milen-sage** [comment]
Let's close this issue since most of the work is done. @afwillia could you open an issue just for the remaining function.
