### ISSUE TITLE
Deploy DCA with a toy data model in INCLUDE

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#300]
Let's deploy an instance of the DCA to shinyapps.io so that the INCLUDE team can customize it.

- [x] determine with the INCLUDE team, the GH org where we can create a fork of the DCA upstream Sage Bionetworks' repo

- [x]  deploy DCA instance configured with example data model to shinyapps.io, using new deployment process

- [ ] setup shinyapps.io account so that INCLUDE team members can administer the app

**Comment by milen-sage** [comment]
Acceptance criteria: INCLUDE shiny app has been deployed on shinyapp.io using the documented deployment instructions.

**Comment by afwillia** [comment]
@milen-sage who is on the INCLUDE team? Who will set up their GH repo?

**Comment by milen-sage** [comment]
@kjflynn does INCLUDE or even better the INCLUDE DMC have a github organization? If yes, we will fork the DCA repository there so that the code of the app can be customized and maintained for INCLUDE, e.g. by Pierrette. We've streamlined the app deployment, so it shouldn't be a big lift for Pierrette to update the app when we have new versions.

**Comment by kjflynn** [comment]
hi @milen-sage yes its here: https://github.com/include-dcc. you appear to be a member!

**Comment by milen-sage** [comment]
@kjflynn @afwillia be added with admin access?

**Comment by kjflynn** [comment]
James should be adding him now, let me know if it doesn't work

**Comment by afwillia** [comment]
App deployed to https://sagebio.shinyapps.io/include-dcc-data_curator-staging/. Waiting for IT to verify

**Comment by afwillia** [comment]
IT has verified and the app is good to go!
