### ISSUE TITLE
DCA dashboard: dataset submission benefit evaluation

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#302]
**Is your feature request related to a problem? Please describe.**
Currently the DCA dashboard shows users what dataset types they are missing, given what data they have already submitted and the schema requirements for that data. In the per project view/tab of the dashboard, the dashboard visualizes the missing requirements for each dataset in the project. A single missing dataset type (e.g. Molecular Test) may be a requirement for multiple datasets: it is shown as missing multiple times. In other words, submitting 'Molecular Test' data will fulfill the requirements for a number of datasets. This is not immediately clear from the dashboard

**Describe the solution you'd like**
For each missing dataset requirement (e.g. Molecular Test), show to the user how much closer they *would* get if they submitted that missing requirement - can indicate percentage and a medal type). That way they could see that just by submitting Molecular Test data they'd get say from 50% completion to 95%.

While this is an enhancement not critical for work, I think it'd be a strong driver of dataset completion. 

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Comment by milen-sage** [comment]
Acceptance criteria: a mock up or prototype of how users would be informed of their dataset submission options and benefits.

**Comment by ychae** [comment]
@rrchai are there any updates for this ticket? I see that you have a draft PR in progress and was wondering if there was anything else you needed?

**Comment by rrchai** [comment]
@ychae right, the draft PR is addressing this ticket. We will review the looking in that PR in our CR meeting tomorrow.
