### ISSUE TITLE
Recreate the folder tree of a project as it appears on Synapse for selection of folders (instead of a dropdown list of all folders in a project)

### ISSUE THREAD

**Issue by jaybee84** [Sage-Bionetworks/data_curator#303]
**Is your feature request related to a problem? Please describe.**

In many projects, where the data come in batches, the top level folder is appropriately labeled with a unique name but the nested subfolders may have non-unique names. For example : 
Top level folder with unique name = `Univ_seqCore_batch1`
Nested subfolder with non-unique name = `raw_reads`
Top level folder with unique name = `Univ_seqCore_batch2`
Nested subfolder with non-unique name = `raw_reads`

When using the Data curator app, all the `raw_reads` folders are present in the dropdown menu and indistinguishable from each other unless manually named with unique names.

This problem is especially exaggerated if the files come from sequencing cores who have processing pipelines that generate hundreds of nested subfolders with non-unique names. This is also the case for outputs for Sage's own nf-core workflows as well. 

**Describe the solution you'd like**

A non-programmatic user of the Data Curator app would like to view the exact folder tree structure that they see on Synapse, to preserve the context of all the non-uniquely named folders.

**How important is this feature?** Select from the options below:
I would rate it as `medium to important` since more and more of our data contributors are starting to rely on the Data Curator for annotation.
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)
• 🌋 Important - it's a blocker and can't do work without it

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

We have a few use cases already.

-- Thanks 
NF-OSI annotations folks :)

**Comment by allaway** [comment]
Also, thanks to @anngvu for the suggestion!! I think that this would really help users with complex project structures. 

I am aware of some packages for using react components in Shiny, but I wonder if it would be feasible to use the SRC entity finder: https://sage-bionetworks.github.io/Synapse-React-Client/#/Other%20Components?id=entityfinder

**Comment by rrchai** [comment]
transfer to #423
