### ISSUE TITLE
Setup DCA instances for CSBC

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#306]
Following up on the INCLUDE dev and prod instances, let's create similar instances for CSBC. 

It looks like these [instructions](https://github.com/Sage-Bionetworks/data_curator/blob/develop/shinyapps_deploy.md) are [aligned](https://github.com/Sage-Bionetworks/data_curator/blob/develop/shinyapps_deploy.md#specify-branches-to-push-to-which-instances) with the DCA deployment docs [here](https://docs.google.com/document/d/1z0DIN9rSoSoIaUttN1NMt7qImYMWhHC0QwO1WVPTvEQ/edit#heading=h.b1ky9n6ks53l). @afwillia @ychae do you think we need another issue for adding the DCA release process as a new doc on github (e.g. RELEASE.md)?

**Comment by milen-sage** [comment]
- [ ] dev instance for CSBC instantiated in shinyapps.io
- [ ] prod instance for CSBC instantiated in shinyapps.io

**Comment by ychae** [comment]
@afwillia - needs more info into where to fork the repo, where should this be set up?
@milen-sage will contact Ashley Clayton

**Comment by milen-sage** [comment]
@afwillia 1st version of the [CSBC data model](https://docs.google.com/spreadsheets/d/1hbG1vdi8a0gc-6psn5VgsBgyMl6IOhDSbHWDuC_8EXo/edit?usp=sharing) that can be converted to json-ld and used in the CSBC DCA app instance.

**Comment by afwillia** [comment]
https://www.shinyapps.io/admin/#/application/5992584

**Comment by milen-sage** [comment]
@afwillia @ychae how can the CSBC team access the admin side of the setup? Should we share lastpass credentials with them?

**Comment by vpchung** [comment]
If it's easier, the credentials can be shared with just me for the time-being.

**Comment by afwillia** [comment]
@ychae @milen-sage The github repo is https://github.com/mc2-center/data_curator and the app has been deployed to
https://sagebio.shinyapps.io/csbc_data_curator_staging/. I shared the LastPass notes with @vpchung

**Comment by milen-sage** [comment]
@ychae @vpchung  just fyi the plan is to deploy a production instance as well. Docs to come on how updates to the two instance work. These would be handled in separate issues.
