### ISSUE TITLE
Clear existing google sheet links when clicking on Get Metadata Template tab

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#31]
Currently the last generated google sheet link is preserved even if there are changes in the 'Select your Dataset' tab, so you have to press the button to generate a new link (which is only slightly different from the link already there; and the link already there actually is not relevant anymore).

**Comment by milen-sage** [comment]
Similarly, when a user uploads a new csv for validation, the previous validation output (e.g. errors or success messages) needs to be cleared.

**Comment by rrchai** [comment]
#125 should resolve the issue for now.
