### ISSUE TITLE
Containerize DCA with schematic

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/data_curator#312]
**Is your feature request related to a problem? Please describe.**
Create a container that users can install to run the app locally. Include schematic so that users don't need to install any dependencies.

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Comment by ychae** [comment]
@afwillia I see that this is marked as done on the Project Board, would it be okay to close this ticket?
