### ISSUE TITLE
DCA retrieves manifest for incorrect project

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#316]
**Describe the bug**
When selecting a project, data type template and folder, the app retrieves the dataset manifest for the wrong project.

**To Reproduce**

Select a project, dataset folder, and dataset type in the HTAN production app:

<img width="2443" alt="Screen Shot 2022-04-14 at 2 27 06 PM" src="https://user-images.githubusercontent.com/41303818/163479806-08248d1a-7767-47b2-9460-0f1d51c8a93c.png">

looks like selection is reflected in properly in the UI

<img width="2440" alt="Screen Shot 2022-04-14 at 2 26 29 PM" src="https://user-images.githubusercontent.com/41303818/163479750-94a2712d-d1e7-4ed9-8561-4c1ef8da59bf.png">

however the generated template contains the manifest for the wrong project (TNP SARDANA: HTA13)

<img width="1938" alt="Screen Shot 2022-04-14 at 2 28 37 PM" src="https://user-images.githubusercontent.com/41303818/163480001-9766dcff-5b99-488b-b597-f804d17dd5ff.png">

**Expected behavior**
The manifest sheet should have contained the manifest for HTAN Duke's project (i.e. starting with HTA6). Duke's manifest is [here](https://www.synapse.org/#!Synapse:syn25149097) and is accurate.

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [ x] Critical 🆘

**Desktop (if applicable, please complete the following information):**
 - OS: [e.g. Mac OS X]
 - Browser [e.g. chrome]
 - Version [e.g. Version 99.0.4844.84 (Official Build) (x86_64)]

**Additional context**
This is critical bug since it exposes info across projects.

**Comment by rrchai** [comment]
@milen-sage thanks for reporting, looking into it.

**Comment by milen-sage** [comment]
Just confirming, it looks like the bug is in on the DCA's end. 

schematic retrieves the right project's manifest from the CLI.

**Comment by rrchai** [comment]
@milen-sage Although I didn't figure which changes cause this bug, but using the latest `schematic` solves the issue. I have updated the prod site and the example ^ now retrieves correct project:
<img width="537" alt="Screen Shot 2022-04-14 at 7 45 26 PM" src="https://user-images.githubusercontent.com/73901500/163495079-9de468ea-28c0-4538-9daf-e3ba9737019c.png">

**Comment by milen-sage** [comment]
Thanks @rrchai! @rrchai and @adamjtaylor would you mind testing if validation and submission (e.g. using CenterA's project) works as expected? We have been making some changes on the schematic 'develop' branch and just want to make sure things work as expected. 

We are moving to a more structured release schedule next sprint, so you won't have to work on bleeding edge code in 'develop'.

**Comment by adamjtaylor** [comment]
I'm not seeing the incorrect manifest issue now in the prod site.... Testing in CenterA validation was working but DCA then was suck at "submitting". This might be a user error on my behalf so I will try again later. @rrchai let me know if you see similar behaviour?

**Comment by rrchai** [comment]
@adamjtaylor Thanks for catching this bug. There is one flag in the submit function missing in DCA. I just created a pr to fix:
- https://github.com/Sage-Bionetworks/data_curator/pull/318

**Comment by milen-sage** [comment]
@rrchai I left a [comment](https://github.com/Sage-Bionetworks/data_curator/pull/318/files#r851452775) on #318. It looks like you might need a minor change when passing the manifest_record_type (i.e. pass "both" as record type).


@adamjtaylor We can chat in more detail, but we introduced these options to gradually move away from creating entities for biospecimen and patients.  This change addresses the issues around fileview limits on number of entity folders. With this code being deployed in the DCA now, we're essentially testing if this feature works as expected and we can transition to creating biospecimen and patient tables, while stopping creating entities. It should also resolve the crash you were experiencing earlier, as @rchai noted.

**Comment by adamjtaylor** [comment]
Validating that this now seems fixed. I am able to validate and submit a manifest in a test project.

**Comment by rrchai** [comment]
That is great. Thank you for testing! @adamjtaylor

**Comment by milen-sage** [comment]
Thanks everyone! @ychae we might want to follow up on Jira?

**Comment by ychae** [comment]
@milen-sage sounds good! I see that @adamjtaylor has already updated the folks on Slack and so I'll go ahead and update and close the Jira ticket. @milen-sage please close this ticket if all ACs have been met, thanks!
