### ISSUE TITLE
Sync schematic REST API endpoints

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/data_curator#321]
@afwillia and @linglp and @rrchai sync up to make sure all of schematic's REST API endpoints have been added to the package. Include endpoints that the dashboard uses.

**Comment by afwillia** [comment]
After talking to Lingling, add the following endpoints

- [ ] get_asset_view_table
- [ ] get_component_requirements

**Comment by linglp** [comment]
@afwillia  get_asset_view_table endpoint has already been merged to develop!
