### ISSUE TITLE
Back to use renv to install r dependencies 

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/data_curator#325]
Our plan is to move away from `shinyapps.io` due to data privacy to our own shiny instance, where should be compatible with  `renv`. Using `renv` is faster and easier to manage r packages versions both locally and remotely.  Let's consider to change back to use `renv`.

**Comment by afwillia** [comment]
renv has been incorporated into the [schematic rest api branch](https://github.com/Sage-Bionetworks/data_curator/tree/schematic-rest-api) and the [Dockerfile](https://github.com/Sage-Bionetworks/data_curator/blob/schematic-rest-api/Dockerfile) uses it
