### ISSUE TITLE
Deploy DCA Staging App for CSBC

### ISSUE THREAD

**Issue by ychae** [Sage-Bionetworks/data_curator#326]
**Describe the solution you'd like**
A staging DCA for CSBC

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience) - will be a blocker in a month

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

AC: 
A staging DCA that's been linked to the CSBC project (dependency on CSBC team restructuring their project) on Synapse that Brynn Z. and Ashley C. can access/use.

**Comment by afwillia** [comment]
The app URL is https://sagebio.shinyapps.io/csbc_data_curator_staging/ @ychae

**Comment by afwillia** [comment]
We will need to update the schema used for this app

**Comment by afwillia** [comment]
In order to create the production instance, I need to tag the repo's main branch. However, per Milen I will wait until the schematic metadata bug is resolved before releasing
