### ISSUE TITLE
Research options for editable table for manifest

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/data_curator#328]
**Describe the solution you'd like**
Add a table with similar functionality to the google sheet for manifest generation. A template with drop down items and editable table would be ideal.

- [x] Editable cells
- [x] Template values for cells
- [x] Dropdown menu for cells

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Mid-term - 2-4 months

**Acceptance Criteria**
A list of javascript or R/shiny packages that can fulfill the above requirements

**Comment by rrchai** [comment]
one existing example: https://github.com/Sage-Bionetworks/data_curator/issues/328

**Comment by milen-sage** [comment]
@ychae note this is research of options only.

AC: has identified candidate libraries for the checkbox-items above. We'd need to start a separate issue to capture requirements to implement this functionality in one of these candidate libraries.

**Comment by afwillia** [comment]
I think this library https://github.com/ejbeaty/CellEdit combined with DT https://datatables.net/ will provide all of the functionality for editing tables in the app.
