### ISSUE TITLE
DCA capture editable table specifications

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#334]
Document specifications for editable table alternative to google sheet manifest template.

AC: a document describing MVP feature-set for editable-table, allowing us to replace google sheets with the editable table alternative, for projects working w/ sensitive data. The feature-set and implementation specification should be sufficiently detailed to allow implementation.

**Comment by ychae** [comment]
@afwillia would you have time this week to sync up on a working session? I'd like to get a brain dump on a google doc to start tracking all of this. @milen-sage is this something you should also be a part of?

**Comment by afwillia** [comment]
@ychae yes I do!

**Comment by afwillia** [comment]
https://docs.google.com/document/d/1xmCUsjAo3ouFzEhFtThQadaWLaC_x2CQilMZJ0r0q1o/edit google doc for specifications

**Comment by milen-sage** [comment]
@afwillia it looks like the set of features are captured in #356. Looks like the next step is to capture more detailed implementation requirements, specs. I.e. for each feature, what is the expected behavior in a bit more detail. For example, we have the feature around dragging values across rows. The corresponding user story/use case could be

> As a data curator, I want to drag values across rows to quickly complete a column or part of a column with the same value, so that I don't have to manually copy and paste cells from one row to the other.

Note how the use case here constrains the requirements to dragging values over rows - e.g. we don't have to implement dragging values across columns on the same row. If we decide this is sufficient for the user then we can outline some of the behavior. 

For example, in datatables - given this is the implementation framework of choice - how is the draw operation defined: is there an existing function in datatables called on down press of a cell corner; how is this function parametrized? Or, is there a configurable datatables mode applied to all cells in the table that makes them draggable; what are the config parameters? 

Similarly, for other features. Some of them will require backend input from schematic, e.g. drop downs and column colors. How are those parametrized. E.g. does schematic need to produce json or javascript code; what's part of the code; is it documented in datatables or do we need to write our own docs; etc.?

@ychae I don't think these features where socialized with users yet, but to me it looks like these are very close to the minimal feature set of what we'd like to support. 

@afwillia @ychae  I'd vote for proceeding with defining specifications for this minimal set of features. This sprint ends tomorrow but let's triage for next one?

**Comment by milen-sage** [comment]
Recent progress is captured in [specification doc](https://docs.google.com/document/d/1xmCUsjAo3ouFzEhFtThQadaWLaC_x2CQilMZJ0r0q1o/edit)
- minimal requirements with some gaps are covered
- gaps in data tables are identified

Next steps: create individual issues for features that are available in DataTables and research alternatives for gaps.
