### ISSUE TITLE
Incorrect Folders listed when selected Project does not have any Folders

### ISSUE THREAD

**Issue by vpchung** [Sage-Bionetworks/data_curator#339]
### **Describe the bug**
DCA assumes a project will have top-level folders readily available.  When a project does not have a top-level folder, the dropdown menu for **Folder:** does not properly reflect that.  It instead shows the folder names from the previously selected Project.  Some screenshots attached below.

### **To Reproduce**
1. Create/add a Synapse Project to the DCA's FileView that only has Files uploaded, no Folders
2. Go to DCA > **Select Your Dataset**
3. Under **Project:**, select the newly added Project

### **Expected behavior**
If a Project is selected and there are no Folders within its scope, the dropdown should either show no items or become inactive.

### **Priority** (select one)
- [x] Minor ⬇️
- [ ] Major 📢
- [ ] Critical 🆘

### **Screenshots**

**DCA - Project with correct Folders listed**
![Screen Shot 2022-06-01 at 3 39 09 PM](https://user-images.githubusercontent.com/9377970/171513882-4fc69228-4c31-4307-86eb-049de75a9b7e.png)

**DCA - Project with incorrect Folders listed**
![Screen Shot 2022-06-01 at 3 39 19 PM](https://user-images.githubusercontent.com/9377970/171514141-555448c5-46fd-4432-b5fc-0d6b617a4e41.png)

**Synapse - the Project causing the issue**
![Screen Shot 2022-06-01 at 3 39 29 PM](https://user-images.githubusercontent.com/9377970/171514206-b5621dfd-46a3-4fd9-bcad-36a35d2affde.png)

**Comment by rrchai** [comment]
Thanks for reporting.  Here are the things we need to update regarding this bug:
1. Display "no item" of folder dropdown when there is no folders in the selected project
2. When they generate the manifest, display warning message to notify the users, you don't have any folders - but still be able to generate manifest
3. During the validation, error messages of no selected folder should be properly added ,thus the submit button should not be shown.
