### ISSUE TITLE
DCA and schematic REST API: research deployment in D&T AWS development account

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#344]

**Comment by milen-sage** [comment]
AC: has coordinated with @thomasyu888  and has identified deployment steps for DCA and REST API docker containers in D&T AWS account.

**Comment by afwillia** [comment]
After chatting with Tom, the best solution to test for our immediate needs is an EC2 instance with the service account. Can also test using Elastic Container Services to help with scalability.

**Comment by thomasyu888** [comment]
Just taking some notes here for my proposed solutions

1. Initially, leverage the service catalog provisioning http://sc.sageit.org/ and create multiple EC2 provisioned products (one for schematic, one for shiny) to become acquainted to the deployment of API services
2. To deploy a service that is more "public" facing, create multiple ec2s with application load balancers that allow you to host the ec2 in a private subnet but expose port 80. 
3. Research ECS to deploy API and shiny server to assist with scalability via the UI. (leave security to me)

**Comment by afwillia** [comment]
I was able to create an EC2 instance with our service catalog and deploy the DCA and schematic containers to it. I can access DCA and schematic through my local browser after exposing the correct ports with [AWS SSM](https://docs.aws.amazon.com/systems-manager/latest/userguide/ssm-agent.html).

Next, we need to address Tom's second point above.
