### ISSUE TITLE
DCA and schematic REST API: D&T AWS deployment test

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#352]

**Comment by milen-sage** [comment]
> Add benchmarking, like shinyloadtest, for multiple DCA instances access 1-2 schematic instances

Let's prioritize the case where multiple DCA instances access one schematic instance: stress testing and benchmarking the schematic REST API performance with multiple concurrent requests.

> how DCA can be configured to access different schematic instances

This^ can wait - we likely won't need support for this case, at least for a while.

**Comment by ychae** [comment]
@afwillia Will work with DPE and IT to access D&T AWS account

**Comment by afwillia** [comment]
Update: schematic is running on an EC2 instance and DCA + dashboard works
