### ISSUE TITLE
DCA and schematic REST API:  scicomp deployment specification

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#353]
AC: stay in sync with Sage IT deployment requirements: if a requirement can be satisfied with small amount of work ( <1 hour) try to complete this sprint; otherwise start gh issues capturing deployment requirements that constitute larger amount of work to tackle in next sprints. Document the current state of deployment requirements at the end of the sprint.

**Comment by milen-sage** [comment]
Continue syncing up with Sage IT.

**Comment by afwillia** [comment]
@milen-sage and @afwillia have been talking with Sage IT as they investigate a new platform for shiny apps. Sage IT is aware that we are using Shiny Server Pro as an interim solution for apps that use sensitive data and they will let us know when a replacement is ready to test.

**Comment by afwillia** [comment]
@ychae we are still waiting to hear back from IT on their new solution.

**Comment by afwillia** [comment]
IT sent an email this morning saying it's likely AWS Fargate + ECS will be the solution moving forward.

**Comment by ychae** [comment]
@afwillia closing since the two teams' work are aligned and will continue to track the work in the #352 ticket
