### ISSUE TITLE
DCA and schematic: Shiny Server Pro deployment specification

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#354]
Shiny Server Pro is currently the only secure hosting service for apps in production that access/process PHI/PII. We don't know when a scicomp solution will be available - see #353. We do know that there are projects like VEOIBD that would contribute sensitive data soon (~Aug) so we'd like to be ready in case #353 is not resolved by then.

AC: DCA has been deployed or a deployment path has been fully spec-ed out so that we can deploy next sprint.

**Comment by milen-sage** [comment]
Start syncing up with Sage IT.

**Comment by afwillia** [comment]
Current procedures are documented on [jira](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/2618359843/Deploy+a+Shiny+Application#Applications-that-are-exposed-to-sensitive-data)

**Comment by afwillia** [comment]
Of note, we have not released a version of DCA that uses the Schematic REST API. @milen-sage for this interim state should we stick with the reticulate workflow? I am hesitant to roll out a new python workflow because we don't have access to the Shiny Server Pro.

**Comment by brucehoff** [comment]
> Shiny Server Pro is currently the only secure hosting service for apps in production that access/process PHI/PII. We don't know when a scicomp solution will be available

Please note that the Shiny Server Pro server IS a sci-comp hosted solution.  The above comment is misleading.  It makes it sound like there is not a sci-comp solution today.

**Comment by milen-sage** [comment]
Thanks for the clarification @brucehoff. I always associated sci-comp with AWS services provided by Sage IT and didn't appreciate the Shiny Server Pro is part of the family there.
