### ISSUE TITLE
Update workflow to use pip release to install schematic

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/data_curator#363]
**Is your feature request related to a problem? Please describe.**
Since the schematic has stable flow for pip release, let's update our workflow to use pip release to install schematic and add a testing instance as well.

**Describe the solution you'd like**

From the discussion with @milen-sage, the ACs of this ticket:
1. Production site  -> tags of DCA + pip release of schematic
2. Staging site, where we could test multiple features together  -> develop/main branch of DCA + pip release of schematic 
3. Testing site (data_curator-testing), where we test single feature at a time -> either branch prefix with `feature-` of DCA or updates from `develop` of schematic

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks
• Mid-term - 2-4 months

**Additional context**

For now, we will keep the life-long `develop` branch. We might plan to implement the combination of `main` + `feature-branches` in the future for two reasons:
1. Avoid collaborators to fetch the wrong branches
2. Easier than maintaining two life-long branches  and less commits history with `squash merge`

**Comment by rrchai** [comment]
I think about the workflow again. My original thought was to make both `develop` and `main` trigger the deployment of `-staging` instance and the `-testing` pulls update from other feature branches. 

I feel what @afwillia implemented in #360 is a better idea: `-staging` should be only pulls from `main` that is more stable branch than `develop`. Here is the developing workflows:

#### If we have a life-long (it will never be deleted after merging) `develop` branch:
1. A developer creates a new feature branch `feat-123` and request a reviewer.
2. If the `feat-123` is approved, it is merged into `develop`, which triggers the deployment of `-testing` site.
3. The maintainers will further test the new feature (only one feature at a time) on the `-testing` instance.
4. Repeat ^ until we are ready to merge all new features from `develop` into `main`.
5. The maintainers create a PR `example-pr` based on `main` from `develop` and request for approval.
6. After the `example-pr` is merged to `main`, it triggers the development of `-staging` site.
7. The maintainers will further test all the new features (1 or 1+) in the  `-staging` site.
8. If no problems, the maintainers will create a tag and make a release. It will update the production site.

The reason pushing to `feat-123` will not update `-testing` site until it's been merged to `develop` is because, if there are multiple ongoing feature branches, they will be conflicts and not stable for testing on a single feature. We could use `-tesing2`, but I don't think it's necessary since most features can be tested locally for CR.

@afwillia  @milen-sage Does the workflow make sense to you?

**Comment by afwillia** [comment]
@rrchai This makes sense to me and is in line with what @milen-sage described. I like the idea to test individual features locally before merging into the develop branch. If it's necessary to test individual feature branches on shinyapps.io, they can be deployed manually to a custom URL using the rsconnect package.

**Comment by milen-sage** [comment]
Yes, this provides a bit more flexibility for people and also is potentially more robust since there are now two instances for testing. And the staging instance can be used to test schemas and other non-code related modifications before updating the production instance. Note that in our current deployment workflow we are restricting people a bit: any time they'd like to test a new schema version on staging they'd have to pull the develop codebase in schematic, for example. This may pull in new untested schematic features in addition to the schema updates they want to check out. If the develop features of schematic have bugs that crash the DCA, then users can't test their schema modifications and are blocked from deploying this on production.
