### ISSUE TITLE
Add a testing release of app to the github deployment workflow

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/data_curator#365]
**Describe the solution you'd like**

- [x] We want to have 3 versions of the data curator app: release, staging, and testing. Release is deployed with a tag and schematic's pypi version. Staging is deployed without a tag and uses schematic's pypi version. Testing is pushed without a tag and uses schematic's develop branch (basically the current staging workflow).

- [x] Update the workflow file for other projects as well, like INCLUDE and CSBC.

- [x] Create new oauth clients for each new testing instance (No need to do this)

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by rrchai** [comment]
- first item is linked to #363
