### ISSUE TITLE
User research on DCA dashboard UI

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#366]
AC: have setup and conducted user research meetings in the week of Jul 25.

**Comment by milen-sage** [comment]
Done - thanks to everyone who participated participating in the dashboard testing and user research

@jaybee84, @avanlinden, @clarisse-lau, @calkinsh !

Dashboard testing scenario is [here](https://docs.google.com/document/d/1Xrt-eT7vgyOkwWchkUfI4vI4AWuaURkhOgkODR7z-n0/edit).

First set of modifications based on user feedback are [here](https://docs.google.com/document/d/1Xrt-eT7vgyOkwWchkUfI4vI4AWuaURkhOgkODR7z-n0/edit)

@ychae will we have access to the recordings once you leave?

**Comment by ychae** [comment]
Recordings are [here](https://drive.google.com/drive/folders/1B9JZdDHtlXJTimIJDgupg2MovUlgj0hR)

Milestone tracking is [here](https://github.com/Sage-Bionetworks/data_curator/milestone/21)
