### ISSUE TITLE
DCA setup and deployment for VEOIBD

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#395]
Deploy DCA on shinyapps.io, after we confirm with @calkinsh that VEOIBD's demo will use synthetic/non-PHI data.

**Comment by milen-sage** [comment]
AC: DCA's test, staging and production instances have been deployed on shinyapps.io and tested.

**Comment by milen-sage** [comment]
@calkinsh have provided a summary of the VEOIBD Synapse project setup [here](https://docs.google.com/document/d/1TmCO6hFQW98Ztq5qpnzCZRxvQtUjRWXFr69n0tLx_9s/edit)

**Comment by afwillia** [comment]
A [testing instance](sagebio.shinyapps.io/veOIBD_data_curator_testing/) has been deployed
