### ISSUE TITLE
Error: Unhandled Exception: Child Task 1216896843 error: Unhandled Exception: 599

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/data_curator#396]
**Describe the bug**
It looks like `rsconnect` is not working to re-deploy the app. The first attempt of [this commit](https://github.com/Sage-Bionetworks/data_curator/actions/runs/2974396420/attempts/1) which changed to use `rsconnect::configureApp(appName = appName, size="xxxlarge")` was able to deploy successfully, but re-running the action failed to deploy the app ([failed attempts](https://github.com/Sage-Bionetworks/data_curator/actions/runs/2974396420)) and same for all [following commits](https://github.com/Sage-Bionetworks/data_curator/actions):

`Error: Unhandled Exception: Child Task 1216896843 error: Unhandled Exception: 599`.

At first, I thought it might be due to the shinyapps.io server issue, but it's still not able to deploy for two days and deployment worked on the [commit](https://github.com/Sage-Bionetworks/data_curator/actions/runs/2957962224) before switching to use `configureApp`. 

**Priority** (select one)
- [ ] Minor ⬇️
- [ ] Major 📢
- [x] Critical 🆘

**Comment by afwillia** [comment]
@rrchai I removed the size argument from `configureApp()` and the app successfully deployed on the first workflow run and a rerun. I'll look into this size option on another branch.

**Comment by rrchai** [comment]
Thanks @afwillia . This issue is solved in this [commit](https://github.com/Sage-Bionetworks/data_curator/commit/00d589aeffef0774443f2fbb51fc2522874a5bb1).

**Comment by afwillia** [comment]
I was hasty and left an unnecessary call to `configureApp()`. This [commit](https://github.com/Sage-Bionetworks/data_curator/commit/11a4ebd3df23f9e016df2ca17f220d77a6f293de) removes the extra call so that `deployApp()` is the last call.

**Comment by rrchai** [comment]
Deployment is also working again in `feat-UI-dashboard`.
