### ISSUE TITLE
DCA: avoid storing manifests as local files

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#399]
Currently, DCA stores csv files on the local file system before validating manifests and before submitting manifests to the asset store. 

In addition, the DCA upcoming dashboard feature implementation saves manifests locally as well, when they are retreated from the REST API.

This makes horizontal scaling and load balancing more challenging, in the context of AWS deployment w/in Sage's production environment.

Instead, based on conversation with @afwillia, we can convert csv dataframes to JSON and pass that to schematic's REST API instead of a csv file; in the case of the dashboard, the REST API can retrieve manifests as dataframes and process them directly in memory w/o a local save.

AC: DCA does not store csv files locally.

**Comment by afwillia** [comment]
I have this feature prototyped, just waiting for the `/model/submit` endpoint to be updated in the schematic develop branch so it can accept a JSON object instead of a file.

**Comment by afwillia** [comment]
Closed with https://github.com/Sage-Bionetworks/data_curator/commit/464b9f2ceb1604932e9a0211749e4baefcec5a8d
