### ISSUE TITLE
DCA: docker containers deployment passing environmental variables

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#400]
Currently the DCA and schematic read-in config variables from config files and some of the config information is stored as github secrets.

In the context of AWS deployment w/in Sage's production environment, we'd need to pass this information as environmental variables to the docker image running the DCA. 

AC: have tested in our development EC2 instance, the DCA docker image runs without the need of reading in config files: all needed config variables are passed to the docker container as environmental variables.

**Comment by afwillia** [comment]
Need to convert elements in config files to environmental variables. 
[oauth_config.yml](https://github.com/Sage-Bionetworks/data_curator/blob/main/example_oauth_config.yml) 

[schematic_config.yml](https://github.com/Sage-Bionetworks/data_curator/blob/main/schematic_config.yml)

**Comment by afwillia** [comment]
Deployed this in a docker container locally and to EC2

**Comment by afwillia** [comment]
Done in this commit to the schematic-rest-api branch ://github.com/Sage-Bionetworks/data_curator/commit/8dfa63fc6fc26491b2b51f7617a710d64b36f13d
