### ISSUE TITLE
Failed to load app in `shinyapps.io` - startup took too long

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/data_curator#406]
**Describe the bug**
@milen reported when accessing to the app in `shinyapps.io`, it failed to load the app with below error.
I also experienced twice, especially trying to start the instance from the sleeping status.
```
Unable to connect to worker after 60.00 seconds; startup took too long. Contact the author for more information.
```

Reloading the page can simply solve the issue, but not sure whether the cause of this error is from shinyapps.io server or app itself. It might be worth checking if moving some loading functions from `global.R` to `server.R` can fix this issue.

**Priority** (select one)
- [x] Minor ⬇️

**Comment by milen-sage** [comment]
I've so far encountered this only with the dashboard demo app - but it is concerning. I'll consult with Sage IT around what part of shinyapps.io deployment could cause that.

**Comment by rrchai** [comment]
<img width="991" alt="Screen Shot 2022-10-04 at 10 41 17 AM" src="https://user-images.githubusercontent.com/73901500/193849748-89e83788-d715-4dec-a36b-c9d60f6c28d7.png">

I can reproduce it when the dashboard-demo instance is initiated from sleeping status. I believe the cause is because there are more files to load in dashboard-demo instance.  I will move the loading/importing functions from `global.R` to `server.R` to see if it will solve the issue.

**Comment by rrchai** [comment]
I realize there are some schematic functions needed to load in `global.R`, otherwise the dashboard will not fail to run. So an alternative way is to increase the startup time in shinyapps.io.
<img width="1449" alt="Screen Shot 2022-10-04 at 1 48 04 PM" src="https://user-images.githubusercontent.com/73901500/193904227-3ce0a048-297f-4cd7-8695-e413e4d272b1.png">

I have increase to 120s and it solves the issue. Once the dashboard is implemented, app maintainers would need to (one-time only) increase the `Startup timeout` (120s should work). We will be able to reduce the loading time by removing importing schematic functions in `global.R` once we have API implemented. 

Closing this issue now and feel free to reopen if the issue persists.

**Comment by milen-sage** [comment]
This looks great - thanks @rrchai!

cc-ing @afwillia since this would be relevant when we roll out the dashboard and users update their apps. I made a note for myself as well.
