### ISSUE TITLE
DCA: expose downloading an Excel spreadsheet as a config and UI option

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#414]
Currently the 'Get Metadata Template' app module allows users to get a link to a Google sheet. Since we can't store PHI data on Google for some projects, instead we'd like to let users download an Excel spreadsheet.

AC: The type of spreadsheet template can be configured in the DCA as a config file parameter: either a Google sheet or an Excel spreadsheet. Depending on the config parameter the DCA should provide an Excel spreadsheet download link/button or a Google sheet one.

**Comment by milen-sage** [comment]
@afwillia you can probably start progressing on the issue before @linglp is ready with [this function](https://github.com/Sage-Bionetworks/schematic/issues/932). But that's the schematic function call that would be relevant for your work.

**Comment by milen-sage** [comment]
@afwillia did you have a chance to incorporate the Excel spreadsheet option in the DCA?

**Comment by afwillia** [comment]
Done as of [this commit](https://github.com/Sage-Bionetworks/data_curator/commit/f48f96ded81d514244a943a27f5355fc67c723b1).

Set the env var `DCA_MANIFEST_OUTPUT_FORMAT` to `excel` or `google_sheet`. The template tab will only show output format-specific options.
