### ISSUE TITLE
DCA: document Excel spreadsheet config and download option

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#416]
Related to #414 - document how the feature is configured and used.

AC: 
- feature configuration  documentation on schema hub
- feature usage documentation in generic user-facing data ingress docs

**Comment by afwillia** [comment]
Starting a DCA deployment documentation page on [schemahub](https://sagebionetworks.jira.com/wiki/spaces/SCHEM/pages/2732818485/Data+Curator+App+Setup+and+Deployment)

And updated the README on the schematic-rest-api-branch.

**Comment by milen-sage** [comment]
@afwillia thanks for starting the docs. I was trying to leave comments on schemahub, alas internet doesn't yet work well in-flight :) 

You mentioned in the schemahub page, the docs are WIP; definitely would need a bit more detail and styling. Similarly in the github readme. You can drop in description of the other env variables as well, for completion?
