### ISSUE TITLE
DCA app disconnects from server when uploading biospecimen template

### ISSUE THREAD

**Issue by calkinsh** [Sage-Bionetworks/data_curator#418]
**Describe the bug**
When the data contributor attempts to submit the csv biospecimen template file, the app disconnects from the server.  I have  experienced the same behavior when trying to submit the same file. 

**To Reproduce**
1. Go to DCA VEOIBD App: https://sagebio.shinyapps.io/VEOIBD_data_curator_testing/
2. Go to the last tab (submission)
3. select biospecimen file to submit (ask Hannah for exact file - I dont want to add it here on public gh) - note that no errors are found when validating
4. submit 

**Expected behavior**
The data template is uploaded with no issue

**Priority** (select one)
- [ ] Minor ⬇️
- [ x] Major 📢
- [ ] Critical 🆘

**Screenshots**
![image](https://user-images.githubusercontent.com/43216173/193644984-b0c06b27-abb3-43e1-a772-ca1fe943729e.png)

**Comment by afwillia** [comment]
@calkinsh  this has been fixed, the app can now submit the biospecimen manifest without disconnecting!
