### ISSUE TITLE
Problematic folder selection with many folders of the same name in the project

### ISSUE THREAD

**Issue by anngvu** [Sage-Bionetworks/data_curator#422]
**Describe the bug**
When a project has many folders with the same name (which can happen with nesting folders in Synapse), one sees only the single name in the selection so it's really hard to select the correct one. 

**To Reproduce**
Select a project where there are multiple Tumor_1 folders nested under Patient_1, Patient_2 etc. folders.
```
Data
| 
|___Patient_1
          |__ Tumor_1
|
|___Patient_2
            |__ Tumor_1
```

![unnamed (2)](https://user-images.githubusercontent.com/32753274/194438644-dcc09bff-f8d3-45c1-b860-17f7a0e536a5.png)

We can try to have PIs mix up the names somewhat to be more distinguishable, but this isn't great in the long run. 

**Expected behavior**
Either append the syn id so folders can be disambiguated or, better yet, addressing **https://github.com/Sage-Bionetworks/data_curator/issues/303** will also solve this problem.

**Priority** (select one)
- [ ] Minor ⬇️
- [x] Major 📢
- [ ] Critical 🆘

**Screenshots**
See above

**Desktop (if applicable, please complete the following information):**

**Additional context**

**Comment by rrchai** [comment]
transfer to #423
