### ISSUE TITLE
DCA: enable support for multiple asset views and schemas

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#424]
Currently the DCA config and logic assumes there's one asset view (i.e. Synapse fileview) and one schema: the app uses this asset view and schema in downstream schematic calls.

We need to change the config file(s) of the DCA to enable specifying a set of asset views and a set of corresponding schemas. The DCA should work with the asset view and the corresponding schema determined based on user input.

AC:

- [ ] config format adjusted to allow specifying multiple asset views and their corresponding schemas
- [ ] added module *prototype* allowing selection of an asset view by a user (e.g. via dropdown)
- [ ] logic added to use the asset view selection above and get the corresponding schema in the config file
- [ ] all operations downstream in the app use this asset view and schema

**Comment by afwillia** [comment]
closed with commit https://github.com/Sage-Bionetworks/data_curator/commit/09795a70681df3da420298a708dc219873d1a3d2

**Comment by milen-sage** [comment]
@afwillia looking forward to see it in action! 

Looking at the commit, I didn't see the config file modifications to allow specifying multiple schemas and fileviews? I might have missed an earlier commit though.

**Comment by afwillia** [comment]
@milen-sage this whole branch is now config-file-less and all configurations are environmental variables. So the synapse IDs of all fileviews are stored as a JSON-encoded env variable.

Also, this only allows for multiple fileviews, I will need to add support for different schemas and mapping the two together.

**Comment by milen-sage** [comment]
@afwillia I see, yes having this branch config-file-less makes a lot of sense since it will get merged for release after we have gone through the [deployment steps for Fargate-based arch](https://sagebionetworks.jira.com/wiki/spaces/IT/pages/2720759990/Deploying+a+Web+Application+to+AWS).

Meanwhile keeping this branch up-to-date with the main branch of the DCA hopefully wouldn't require too many merge conflicts over the next couple of months.

For schemas, I think we could be scrappy for now actually. Assume that schematic will be able to retrieve the necessary schema based on the fileview. We will add an endpoint for that. So closing the issue sounds good.

**Comment by afwillia** [comment]
For hindsight: since the fileviews are passed as the `DCA_SYNAPSE_MASTER_FILEVIEW` environmental variable and not included in the code, here is how to specify them:

**One fileview without its name**
`'["syn33715412"]'`

**One fileview with names**
`'{"mock dca fileview (syn33715412)":["syn33715412"]}`

**2+ fileviews without names**
`'["syn33715412", "syn36744684"]'`

**2+ fileviews with names**
`'{"mock dca fileview (syn33715412)":["syn33715412"], "test-dca-fileview (syn36744684)":["syn36744684"]}'`
