### ISSUE TITLE
DCA: apply different skin depending on fileview selection

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#427]
Given a fileview selection, apply an app style, corresponding to that fileview. The style name can be specified in the app config for each fileview. 

AC: a different style, i.e. skin, is applied when a user selects a fileview.

**Comment by milen-sage** [comment]
@afwillia you can reach out to @rrchai on how to dynamically apply styles to all app modules.

**Comment by afwillia** [comment]
@milen-sage should we have a default skin for projects that don't have or want to use their own?
