### ISSUE TITLE
DCA: Add automated security scan for the docker container

### ISSUE THREAD

**Issue by afwillia** [Sage-Bionetworks/data_curator#432]
**Is your feature request related to a problem? Please describe.**
Add a CI/CD workflow to scan the DCA image for vulnerabilities. Consider docker scan or dependabot

**How important is this feature?** Select from the options below:
• 🌗 Medium - can do work without it; but it's important (e.g. to save time or for convenience)

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Comment by milen-sage** [comment]
We should do the same for the schematic docker container and repo.

**Comment by afwillia** [comment]
dependabot was already activated for the data curator repo!
