### ISSUE TITLE
TT1 DCA: DCC selection UI

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#451]
https://sagebionetworks.jira.com/browse/DCA-22

**Comment by afwillia** [comment]
Is there a schematic REST API endpoint to get all of the asset views a user has access to?

**Comment by milen-sage** [comment]
@afwillia nope, but all asset views should be in the config, so the app should be able to retrieve them? 

Speaking of views, we'd probably also want to specify the names of the asset views - in addition to the view IDs - in the config, for readability in the UI. E.g. view with synXXXXXX would correspond to DCC HTAN; view with synXXXXXX1, would correspond to DCC YYY; etc..

**Comment by afwillia** [comment]
@milen-sage yes, that's currently how the app is set up. The user sees all of the programmed asset views regardless of their ability to access them. I interpreted this request to reduce the list the user sees to only asset views they can access. Also, the asset view name and synapse ID are both already displayed in the dropdown menu.

**Comment by milen-sage** [comment]
Ah I see: your question is about how do we know which user has access to what asset views so that we don't show them the asset views they don't have access to. There isn't a dedicated endpoint for that yet. 

The API call that retrieves all projects a user has access to would return an empty set (I think an empty list) if the user doesn't have access to the config view. But I'm not sure 

1. if this API call allows you to specify the asset view for which to retrieve user's project (or the view is retrieved from the schematic config currently)
2. how much time does the call take, especially for larger asset views (iterating over multiple asset views may be too time consuming)

However, the Synapse REST API does have an endpoint that allows you to check if a user has access to a given Synapse entity. This may be the way to go short term (i.e. when a user logs in the app checks whether the user has access to each of the asset views in the app's config).
