### ISSUE TITLE
TT1 Enable customizable manifest basenames in the app

### ISSUE THREAD

**Issue by rrchai** [Sage-Bionetworks/data_curator#457]
Based on the discussion with @milen-sage and @afwillia, the hardcoded `synapse_storage_manifest.csv` is currently used as default manifest name in the app. The `schematic` has updated to use customizable [manifest_basename](https://github.com/Sage-Bionetworks/data_curator/blob/e13593c27378f4c02db1d0d448ab57c45c4f53c2/schematic_config.yml#L11) in `schematic_config.rds`. Thus, using the hardcoded file name is limited now, since the new uploaded manifests are possible to have names other than `synapse_storage_manifest.csv`.

There are two places I notice needed to change:
- [ ] The manifest is stored locally as `synapse_storage_manifest.csv` and then upload the file with hardcoded filename to synapse during submissions. It should be stored as `{manifest_basename}_{Component}.csv` 
https://github.com/Sage-Bionetworks/data_curator/blob/e13593c27378f4c02db1d0d448ab57c45c4f53c2/server.R#L415
- [ ] Dashboard should filter both `synapse_storage_manifest` and `manifest_basename` to include old and new manifests from fileview table. I suggest to use `grep/grepl` the string patterns instead.
https://github.com/Sage-Bionetworks/data_curator/blob/e13593c27378f4c02db1d0d448ab57c45c4f53c2/functions/dashboardFuns.R#L12

**Comment by rrchai** [comment]
@milen-sage Is the `validateModelManifest` now automatically extend `manifest_basename` with `{Component}`, or the manifest should be named as `{manifest_basename}_{Component}.csv` in the first place. Also, can you please confirm if `{manifest_basename}_{dataType}.csv` is the correct format of manifest name?

@afwillia `{Component}` can be retrieved using `selected$schema()`.

**Comment by rrchai** [comment]
@milen-sage @afwillia Does this ticket have the green light to proceed? I can work on this ticket if it has not been started.

**Comment by afwillia** [comment]
@rrchai yes - I started working on it here https://github.com/Sage-Bionetworks/data_curator/compare/develop...develop-fix-52-dashboard, but there are some extra differences showing up that I want to resolve before creating a PR.

**Comment by rrchai** [comment]
@afwillia Cool! Thanks for looking into it. Feel free to let me know if anything I can help.

**Comment by afwillia** [comment]
This has been incorporated into the REST api branch https://github.com/Sage-Bionetworks/data_curator/tree/beta-schematic-rest-api
