### ISSUE TITLE
DCA: remove data dashboard from release code

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#459]
Based on HTAN's request [here](https://github.com/ncihtan/HTAN-data-curator/issues/47#issuecomment-1376231406) we'd like to turn off the DCA standards compliance deployment for now.

AC: standards compliance dashboard is not shown in the DCA until #457 is resolved and the HTAN team gives us a go-ahead pending user ramp up to dashboard functionality

**Comment by afwillia** [comment]
This is fixed as of [PR 460](https://github.com/Sage-Bionetworks/data_curator/pull/460).
