### ISSUE TITLE
DCA: consult with AMP-AD on app config

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#475]
@avanlinden has been testing the DCA with AMP-AD's project. The app had been working at least up to spreadsheet templates generation, but it's been persistently crashing in the last weeks.

The crash is, possibly, due to config mismatch with latest versions of schematic: the app may be setup as a testing instance pulling the latest dev version of schematic on redeployment. If that's the case, let's set it up as a staging or production instance (or add these instances so that we avoid the instability of a testing instance setup).

@afwillia could you reach out to @avanlinden for a consult on the current state of the app and how to get it back up and running (at least for the default example data model).

**Comment by MiekoHash** [comment]
Hi @afwillia , This ticket came up in D&T PM Stand Up as needing a follow-up. If not already, could you plan on reaching out to @avanlinden this week? Thanks in advance.

**Comment by MiekoHash** [comment]
Hi @afwillia , In today's D&T PM Stand Up, I learned that this has been agreed that "not critical will use schematic to create data model". @milen-sage , I think we can close this issue unless we are trying to repurpose it for something else.

**Comment by milen-sage** [comment]
@afwillia @MiekoHash I think the priority on this issue is lower given these conversations. But we still would like to understand why they were experiencing the issue and circle back at a later time to resolve it. 

Let's leave the issue in the backlog although we are not going to work on it this sprint.

**Comment by afwillia** [comment]
@milen-sage @MiekoHash actually, I wrapped this up last week but forget to update the ticket. Closing this now!

**Comment by milen-sage** [comment]
Great to hear the config of the app works for AMP-AD for testing purposes again.

**Comment by MiekoHash** [comment]
Great! Thanks, Anthony. cc: @abbywall for D&T Project Board update.
