### ISSUE TITLE
Detect manifests with large numbers of empty columns/rows prior to validation

### ISSUE THREAD

**Issue by allaway** [Sage-Bionetworks/data_curator#511]
**Is your feature request related to a problem? Please describe.**
I recently uploaded a manifest that was provided by a community member. This manifest was exported from excel, and had 2 rows of annotations, and 9998 rows of blanks. I clicked "validate," which caused the app to validate a very large number of values. The app appeared to freeze (could posibly have just been taking a very long time). I was unable to load new instances of the app and had to restart the app from the shinyapps.io dashboard to fix the issue. 

**Describe the solution you'd like**
The app should test for this edge case _before_ validating and remove blank rows and blank columns without headers.

**How important is this feature?** Select from the options below:
• 🏝 Low - it's an enhancement but not crucial for work

**When will use cases depending on this become relevant?** Select from the options below:
• Short-term - 2-4 weeks

**Additional context**
This seems like an error that an end user would be unable to recover from. I think the part about being unable to load new instances of the app should no longer be an issue when we switch to multi-tenant. Also, we aren't running the latest DCA in anticipation of migration to multi-tenant, so it's possible that this has already been fixed here.

**Comment by afwillia** [comment]
Thanks for reporting this. I moved it to our backlog and will plan to fix this in the multitenant roll out.

**Comment by afwillia** [comment]
I can reproduce this using the schematic's prod and dev REST API. Reminder to check if this can be fixed in schematic.

**Comment by allaway** [comment]
Heya, I just wanted to mention that we had another user encounter this issue today. I am curious if this is already resolved in the multitenant DC app or in schematic?

**Comment by afwillia** [comment]
@allaway yes, this has been resolved in the develop branch/multitenant DCA. Blank records are trimmed after uploading the csv.

**Comment by allaway** [comment]
Awesome - thanks! I will close this then.
