### ISSUE TITLE
Add border markup to google sheet resolve sheet export to excel

### ISSUE THREAD

**Issue by milen-sage** [Sage-Bionetworks/data_curator#64]
If allowable in google sheet's API add border formatting markup explicitly and check if exports to excel and openoffice format show borders correctly. Currently borders in exported documents are not shown for all cells whose background colors has been specified in google sheet. See @vthorsson comment [here](https://github.com/Sage-Bionetworks/HTAN-coordination/issues/129#issuecomment-620220922); others have pointed to this issue as well. 

Furthermore, support for exporting metadata google sheets to Excel introduces a stricter limit on number of dropdown items compared to google sheet. Google sheet limit is 500; Excel's limit is 256. We need to handle that.

**Comment by milen-sage** [comment]
@nithyav21 this is related to BU's request for exporting metadata templates to Excel.

I updated our backend and @xdoan is integrating and testing the changes that resolve Excel export. 

As indicated in our thread with BU, we should have these enhanced excel export features ready for them to use tomorrow.

@nithyav21 the current solution to Excel's dropdown limit (~256 entries) is to truncate the valid values in our clinical data model when generating google sheets (e.g. for Diagnosis); we still keep the valid values in our data model and can validate input outside the truncated set. In general, a better solution, as we discussed, might be to restrict the overall set of valid values to the ones that are relevant for HTAN. But I think the current solution is likely to work for BU.

Another option would be to direct centers to fill in their manifest in OpenOffice instead of Excel - it has full support of the number of valid values in our dropdowns (go free open software!), but again up to the limit of google sheet (i.e. 500).

**Comment by milen-sage** [comment]
@nithyav21 you can check how this spreadsheet exports to Excel:
https://docs.google.com/spreadsheets/d/1TDdJ8RCrG3l56pReA5KeMRCMCpG-v-qHvRzmCUVU1EE/edit?usp=sharing

I have tested in Excel on Mac OS X and it works for me (I have also tested with OpenOffice and that works as well).

**Comment by nithyav21** [comment]
Thanks @milen-sage 
I'm able to download the sheet as excel but I'm not seeing anything in the dropdown for primary diagnosis, site of resection or biopsy and tissue or tumor of origin (these are the ones with a lot of enumerations). I'm able to see values in drop-downs for a few other fields. Not sure if the truncate to ~256 values is working for me, maybe I'm missing something.

**Comment by milen-sage** [comment]
I see what you mean @nithyav21 - looking into it now.

**Comment by milen-sage** [comment]
Thanks for the feedback @nithyav21 this all should be resolved now; a sample diagnosis template here:
https://docs.google.com/spreadsheets/d/1JAM-KLe5peC6XSS7gDwtIcQirm_in9W80nD4837tk7w/edit?usp=sharing 

Please try exporting it^

**Comment by nithyav21** [comment]
@milen-sage - Yes, I can now see valid values in the column when I see valid values in the dropdown now for the fields mentioned above.

While we are at it, can we also add some Diagnosis attributes that I talked about to you earlier this week? (part of Tier 1 and updates to Tier1 (Mar 2020)). As I mentioned, these are some tumor specific suggestions from centers already covered in GDC Tier 1, so it would be great to add this to the template in data curator. Thanks! 


<table class="tg">
<thead>
  <tr>
    <th class="tg-0thz">Attributes that need to be added to Diagnosis</th>
    <th class="tg-0thz">Relevant Dictionary</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-gd2f">supratentorial_localization</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">secondary_gleason_grade</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">primary_gleason_grade</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">ovarian_surface_involvement</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">ovarian_specimen_status</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">non_nodal_tumor_deposits</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">non_nodal_regional_disease</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">mitosis_karyorrhexis_index</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">micropapillary_features</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">medulloblastoma_molecular_classification</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">iss_stage</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">irs_stage</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">irs_group</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">international_prognostic_index</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">inss_stage</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">inrg_stage</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">inpc_histologic_group</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">inpc_grade</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">igcccg_stage</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">gleason_grade_group</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">cog_rhabdomyosarcoma_risk_group</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">cog_neuroblastoma_risk_group</td>
    <td class="tg-za14">Tier 1 Dictionary</td>
  </tr>
  <tr>
    <td class="tg-gd2f">who_nte_grade</td>
    <td class="tg-za14">Mar2020 updates</td>
  </tr>
  <tr>
    <td class="tg-gd2f">who_cns_grade</td>
    <td class="tg-za14">Mar2020 updates</td>
  </tr>
  <tr>
    <td class="tg-gd2f">tumor_grade</td>
    <td class="tg-za14">Mar2020 updates</td>
  </tr>
  <tr>
    <td class="tg-gd2f">tumor_depth</td>
    <td class="tg-za14">Mar2020 updates</td>
  </tr>
  <tr>
    <td class="tg-gd2f">pregnant_at_diagnosis</td>
    <td class="tg-za14">Mar2020 updates</td>
  </tr>
  <tr>
    <td class="tg-gd2f">margins_involved_site</td>
    <td class="tg-za14">Mar2020 updates</td>
  </tr>
  <tr>
    <td class="tg-gd2f">margin_distance</td>
    <td class="tg-za14">Mar2020 updates</td>
  </tr>
  <tr>
    <td class="tg-gd2f">lymph_node_involved_site</td>
    <td class="tg-za14">Mar2020 updates</td>
  </tr>
  <tr>
    <td class="tg-gd2f">greatest_tumor_dimension</td>
    <td class="tg-za14">Mar2020 updates</td>
  </tr>
  <tr>
    <td class="tg-gd2f">gleason_patterns_percent</td>
    <td class="tg-za14">Mar2020 updates</td>
  </tr>
  <tr>
    <td class="tg-gd2f">gleason_grade_tertiary</td>
    <td class="tg-za14">Mar2020 updates</td>
  </tr>
</tbody>
</table>

**Comment by milen-sage** [comment]
@nithyav21 - let's follow up with Karla regarding excel export - the functionality is in the data curator app now. They can test it out. 

Meanwhile, yes, I'll update the clinical data as we discussed.
