### ISSUE TITLE
Show the selection of project, dataset, and template in the other two tabs

### ISSUE THREAD

**Issue by xindiguo** [Sage-Bionetworks/data_curator#71]
When testing for metadata validation, the app was timed out and I realized I need to go to make the selection of dataset and template again after refresh the app. I wonder if it makes sense to show the selection of project, dataset, and template in the other two tabs as well to remind the user which dataset and template have been selected?

**Comment by xdoan** [comment]
thank you! related to #39 and we are hoping to use some iAtlas proposed work to also help here.

**Comment by milen-sage** [comment]
Is this the same as #39 ?
