### ISSUE TITLE
Create a stable branch (for use in the Data Curator App setup documentation)

### ISSUE THREAD

**Issue by BrunoGrandePhD** [Sage-Bionetworks/data_curator#99]
Currently, the documentation refers to the `shiny-server-1.2.1.rc1` branch. However, in the final version of the documentation, we should refer to a primary stable branch. Based on conversation on @xdoan, this branch will be named `shiny-server-main`.

**Comment by xdoan** [comment]
created and now the default branch

**Comment by BrunoGrandePhD** [comment]
Beautiful! Thanks, @xdoan! I'll update the setup docs accordingly!
